### PR TITLE
Icon: add upload, save, and pin icons

### PR DESCRIPTION
**Pull request by ichittaro-Ithaka**
**This change:** (check at least one)

- [X] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [X] No

**Is the:** (complete all)

- [X] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [X] Test suite(s) passing?
- [X] Code coverage maximal?
- [X] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
- Resolves https://github.com/ithaka/pharos/issues/790
- Resolves https://github.com/ithaka/pharos/issues/795
- Resolves https://github.com/ithaka/pharos/issues/787
- Resolves https://github.com/ithaka/pharos/issues/786

**How does this change work?**
Adds svgs

### CODE REVIEW

**Review by daneah — CHANGES_REQUESTED** [review]
@ichittaro-Ithaka Thanks for adding these! It looks like you may not have the [pre-commit hooks](https://github.com/ithaka/pharos/blob/develop/docs/development/conventions/git.md#pre-commit-hooks) installed for this repository—I think your SVGs are probably failing linting at the moment (try `yarn lint`)—the SVG files needed for the icons actually need to have the enclosing `<svg ...></svg>` removed.

Viewing the Storybook, the `save-and-close` icon is misaligned. @nkamau can you re-export your provided SVG with the right viewbox?

**Comment by nkamau** [comment]
> @ichittaro-Ithaka Thanks for adding these! It looks like you may not have the [pre-commit hooks](https://github.com/ithaka/pharos/blob/develop/docs/development/conventions/git.md#pre-commit-hooks) installed for this repository—I think your SVGs are probably failing linting at the moment (try `yarn lint`)—the SVG files needed for the icons actually need to have the enclosing `<svg ...></svg>` removed.
> 
> Viewing the Storybook, the `save-and-close` icon is misaligned. @nkamau can you re-export your provided SVG with the right viewbox?
> 
> Screenshot 2024-08-02 at 12 04 44

That's bizarre. In Figma the save-and-close is correctly lined up in the icon grid. 
Screenshot 2024-08-02 at 1 29 13 PM
I'll try tinkering around to see what's up...

**Comment by nkamau** [comment]
> @ichittaro-Ithaka Thanks for adding these! It looks like you may not have the [pre-commit hooks](https://github.com/ithaka/pharos/blob/develop/docs/development/conventions/git.md#pre-commit-hooks) installed for this repository—I think your SVGs are probably failing linting at the moment (try `yarn lint`)—the SVG files needed for the icons actually need to have the enclosing `<svg ...></svg>` removed.
> 
> Viewing the Storybook, the `save-and-close` icon is misaligned. @nkamau can you re-export your provided SVG with the right viewbox?
> 
> Screenshot 2024-08-02 at 12 04 44

Save   Close
Maybe this'll work...I moved the circle more into the save icon.

**Comment by nkamau** [comment]
> @ichittaro-Ithaka Thanks for adding these! It looks like you may not have the [pre-commit hooks](https://github.com/ithaka/pharos/blob/develop/docs/development/conventions/git.md#pre-commit-hooks) installed for this repository—I think your SVGs are probably failing linting at the moment (try `yarn lint`)—the SVG files needed for the icons actually need to have the enclosing `<svg ...></svg>` removed.
> 
> Viewing the Storybook, the `save-and-close` icon is misaligned. @nkamau can you re-export your provided SVG with the right viewbox?
> 
> Screenshot 2024-08-02 at 12 04 44

Icon:
Save   Close

Maybe that'll work...I moved the circle more inside the save icon. Hoping that'll line it up more.

**Comment by ichittaro-Ithaka** [comment]
@daneah after running yarn lint, I came across these issues that I couldn't seem to resolve. I first removed the svg tags, but the black color issues persisted & icons started looking strange following this change. Is the right solution to add these to the fillAllowList? Or is there some other solution you would recommend 
Screenshot 2024-08-02 at 2 02 37 PM

**Comment by daneah** [comment]
@ichittaro-Ithaka the removal is the correct action, and does result in a technically invalid standalone SVG file, but the icon should still look correct in storybook.

Regarding the other errors, you likely need to remove the `fill` attribute; there's nothing that should need to be reconfigured to allow.

**Comment by nkamau** [comment]
> @ichittaro-Ithaka Thanks for adding these! It looks like you may not have the [pre-commit hooks](https://github.com/ithaka/pharos/blob/develop/docs/development/conventions/git.md#pre-commit-hooks) installed for this repository—I think your SVGs are probably failing linting at the moment (try `yarn lint`)—the SVG files needed for the icons actually need to have the enclosing `<svg ...></svg>` removed.
> 
> Viewing the Storybook, the `save-and-close` icon is misaligned. @nkamau can you re-export your provided SVG with the right viewbox?
> 
> Screenshot 2024-08-02 at 12 04 44

Save   Close
Done, y'all. Note: I am aware that the circle is filled with #FFFFFF. Decision: Currently save & close is in use on Forum bc of bulk save. I checked out our other platforms and our action icons are always resting on white backgrounds and I don't forsee it being used on a colored background.

Hoping this alignment works.

**Comment by daneah** [comment]
@nkamau would an alternative be to do a boolean difference between the disk and the circle so that it cuts off that part of the disk altogether and the circle can have a transparent background?

**Comment by nkamau** [comment]
> @nkamau would an alternative be to do a boolean difference between the disk and the circle so that it cuts off that part of the disk altogether and the circle can have a transparent background?

! I tried to do something similar in Figma (we have subtract, union, intersect, and exclude), but none worked! However, I think I fixed it...Let's see...

save-and-close1

**Comment by nkamau** [comment]
> @nkamau would an alternative be to do a boolean difference between the disk and the circle so that it cuts off that part of the disk altogether and the circle can have a transparent background?

! I tried to do something similar in Figma (we have subtract, union, intersect, and exclude), but none worked! Took an hour break, and I _think _ I may have cracked the code with adding some grouping and unions...Let's see...

save-and-close1

**Comment by daneah** [comment]
@ichittaro-Ithaka I see the `fill="white"` you had to remove from the `mask` element in the `save-and-close` icon makes the icon display improperly...seeing if there's a good way to add that particular exception to the linting rule.

**Comment by daneah** [comment]
Grr, the `fill-rule` or `clip-rule` are still mildly getting in the way, I think:

Screenshot 2024-08-02 at 16 38 15

**Comment by nkamau** [comment]
> Grr, the `fill-rule` or `clip-rule` are still mildly getting in the way, I think:
> 
> Screenshot 2024-08-02 at 16 38 15

I think I potentially found a solution to fix that because I see the circle that i "unioned" stayed transparent. May work, may not. Sort of a hail mary. Could you try these?

Save-and-close:
save-and-close2

Save-changes:
Save-changes

**Comment by daneah** [comment]
@nkamau Those look good! Last thing: I'm noticing the `pin` icon is filled in, for some reason, even though I can't really tell why it would be. Thoughts?

**Comment by nkamau** [comment]
> @nkamau Those look good! Last thing: I'm noticing the `pin` icon is filled in, for some reason, even though I can't really tell why it would be. Thoughts?

That's weird...There's no fill in the design. I think I'll just remake it.

**Comment by nkamau** [comment]
> @nkamau Those look good! Last thing: I'm noticing the `pin` icon is filled in, for some reason, even though I can't really tell why it would be. Thoughts?

Is this pin working? (For after the weekend!) :
Pin

**Comment by daneah** [comment]
@nkamau that pin looks better on @ichittaro-Ithaka's latest build! @ichittaro-Ithaka if you can fix your merge conflicts (I think a `yarn install` after merging latest `develop` into your branch should do it) I think we can get this merged.

**Comment by ichittaro-Ithaka** [comment]
@daneah let me know if I followed those steps properly!

**Comment by daneah** [comment]
@ichittaro-Ithaka it appears you did, but now we're maybe running into some Pharos site build oddities...investigating. Sorry this has been a pain 😅

**Comment by ichittaro-Ithaka** [comment]
@daneah no worries at all! Let me know if there's anything else I should check out

**Comment by daneah** [comment]
I reconfigured the site build process to use Node 20 instead of Node 18, and it's happier now. The status isn't reflected here. I'll merge this!

**Pull request merged**
