### PR TITLE
Updating thumbs up/down filled icons

### PR DESCRIPTION
**Pull request by rehanabbasi**
**This change:** (check at least one)

- [x] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
This PR updates the `thumbs-up-filled` and `thumbs-down-filled` icons in the pharos icon set

### CODE REVIEW

**Review by drewgingerich — APPROVED** [review]

**Review by daneah — CHANGES_REQUESTED** [review]
@rehanabbasi @fswlee the new icons aren't centered within the viewbox:

Screenshot 2023-07-27 at 19 30 58

**Comment by fswlee** [comment]
thumbdown-filled
thumbup-filled


will this work @rehanabbasi ?

**Comment by fswlee** [comment]
@rehanabbasi can we make the updates to these icons? thank you!

**Comment by daneah** [comment]
These icons were added in #566 and these new versions are [not visually any different per Chromatic](https://www.chromatic.com/test?appId=60919c26122bd50039b34644&id=65eb8b6850e1ba8cf2dbc09c), so I am closing this pull request.

**Pull request closed without merging**
