### PR TITLE
Gatsby 5 upgrade

### LINKED ISSUE #632: Site: Fix development environment
**Expected behavior**
Running `yarn site:develop` should run pharos site successfully locally

**Actual behavior**
Locally, I am seeing blank page and console errors after running `yarn site:develop`. (More in Additional Information)

**Steps to reproduce the issue**

1. On `develop` branch, run `yarn site:develop`
2. Gatsby service with pharos site docs, should be running on `http://localhost:8000`
3. Visiting, `http://localhost:8000` displaying blank page and having above mentioned console error (from **Actual Behavior**)

**Screenshots or code**
If applicable, add screenshots or code to help explain the issue.

**Pharos version**
`pharos site`: 5.13.4

**Your environment**

- OS: MacOS
- Browser: Chrome
- Version: 117.0.5938.149

**Additional information**

After running `yarn site:develop`, I see blank page with below console error:  
`Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ../../node_modules/gatsby-plugin-mdx/loaders/mdx-components.js`. 

Also, I see this `warn` message during build process: `warn ../../node_modules/gatsby-plugin-mdx/wrap-root-element.js
Attempted import error: 'plugins' is not exported from './loaders/mdx-components' (imported as 'mdxPlugins').`

### LINKED ISSUE #717: Site: Upgrade to Gatsby 5
**The problem**

I want to use the latest versions of our dependencies so that I can take advantage of their new features, security, and ecosystem.

**The solution**

Upgrade to Gatsby 5

**Additional information**

I believe the main work will be #718 and updating to React 18 (just the dependency; no implementation work involved)

### LINKED ISSUE #718: Upgrade to MDX 3
**The problem**

I want to use the latest versions of our dependencies so that I can take advantage of their new features, security, and ecosystem.

**The solution**

Upgrade to MDX 3

**Additional information**

This might be a bit involved. Namely:

- MDX > 1 does not allow expressions, so any logic must be in another module and imported, if needed.
- MDX linting seems to get confused about closing tags that are on their own lines—maybe this is improved when all the related packages are upgraded together at the right time.

### LINKED ISSUE #756: Loading spinner page on pharos.org doesn't load
**Expected behavior**
The page should load as the rest of the component pages do with documentation.

**Actual behavior**
The page is blank and appears to be broken

**Steps to reproduce the issue**

1. Go to https://pharos.jstor.org/components/loading-spinner
2. Observe a blank page.

**Additional information**
It is possible that this component does not have written documentation and that that the page on pharos.org needs to be designed.

### PR DESCRIPTION
**Pull request by daneah**
**This change:** (check at least one)

- [ ] Adds a new feature
- [ ] Fixes a bug
- [x] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**

- Fixes #632 
- Resolves #717 
- Closes #718 
- Fixes #756

**How does this change work?**

- Remove use of MDX across the Pharos site, significantly removing and reducing hangups with compatibility between MDX, Gatsby, and Prettier
  - Keep MDX for Storybook intro docs, as that is the only way to generate top-level documentation pages using built-in Storybook behavior. This is rather inconsequential compared to the overall MDX usage we had.

### CODE REVIEW

**Comment by brentswisher** [comment]
I was getting an error when building that doesn't show up when running yarn develop, didn't have  a ton of time to look into it, something with SSR

**Comment by brentswisher** [comment]
I'm meeting with David tomorrow to talk about the examples design a bit too, fwiw

**Comment by daneah** [comment]
@brentswisher @david-corneail let us not let that discussion prevent us from merging this change, as this represents literal months of struggle and frustration—we need to lock in what value we have here and iterate.

The SSR issue is particularly frustrating as it is not of large importance to this project—but we should prioritize fixing it nonetheless mostly again to be able to get past this initial large hurdle. I spent a little bit looking at it and am able to get around it on a page-by-page basis, but it's tedious and doesn't feel like the correct overall approach.

**Comment by brentswisher** [comment]
So [this](https://github.com/ithaka/focus-trap/blob/039d532b7a773b1cc654e7b3ff5815d044158f15/src/lib/focus-trap.ts#L16) seems to be the cause of the error 😞

I'm not familiar with `focus-trap`, I could just add a conditional to it, but I note it hasn't been updated in 3 years, which is 2 years later than what it is forked from. Wondering if there is a better solution for this at today, or a different library we could just switch to that is actively maintained - I'll chat with @sirrah-tam to see

**Comment by eslawski** [comment]
Bit of an aside, but we might want to look at the newly available [Popover API](https://developer.chrome.com/blog/new-in-web-ui-io-2024#the_popover_api) at some point in the future which I understand has some amount of focus trapping capabilities out of the box.

**Comment by brentswisher** [comment]
👍 @eslawski long term I agree, #755 and #347 will likely make the focus-trap less necessary

**Comment by brentswisher** [comment]
@daneah - @david-corneail and I updated the examples, in some of them (links, breadcrumbs) it wasn't entirely clear they were an example. I also extracted it into a component so we can iterate on it later easier

## Before:
Screenshot 2024-07-18 at 11 22 07 AM
Screenshot 2024-07-18 at 11 22 55 AM


## After:
Screenshot 2024-07-18 at 11 19 23 AM

Screenshot 2024-07-18 at 11 26 49 AM

**Review by sirrah-tam — APPROVED** [review]

**Review by brentswisher — APPROVED** [review]

**Pull request merged**
