### PR TITLE
Icons: add thumbs up down icons

### PR DESCRIPTION
**Pull request by rehanabbasi**
**This change:** (check at least one)

- [x] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
Adds thumbs up/down icons

### CODE REVIEW

**Comment by daneah** [comment]
@rehanabbasi you'll need to remove the enclosing `<svg>` as those get added dynamically in the code; see the linting job failure for more detail. You should be able to run `yarn lint` locally to see this as well.

**Review by chrisjbrown — APPROVED** [review]

**Comment by chrisjbrown** [comment]
@rehanabbasi do you need to supply filled and unfilled icons? or can the consumer decide that?

**Comment by rehanabbasi** [comment]
> @rehanabbasi do you need to supply filled and unfilled icons? or can the consumer decide that?

@chrisjbrown I had specified unique icon names for each of those variants!

**Comment by chrisjbrown** [comment]
> > @rehanabbasi do you need to supply filled and unfilled icons? or can the consumer decide that?
> 
> @chrisjbrown I had specified unique icon names for each of those variants!

I mean to say
are those variants necessary?
would it be better to allow the consumer to style those icons

**Comment by rehanabbasi** [comment]
> > > @rehanabbasi do you need to supply filled and unfilled icons? or can the consumer decide that?
> > 
> > 
> > @chrisjbrown I had specified unique icon names for each of those variants!
> 
> I mean to say are those variants necessary? would it be better to allow the consumer to style those icons

Understood - so I think we already have filled and unfilled icon example in the font set (`checkmark-filled-circle
` and `checkmark-inverse` ) where we provide separate icons for each filled and unfilled variant - so was following that!

**Review by chrisjbrown — APPROVED** [review]

**Comment by daneah** [comment]
@rehanabbasi @chrisjbrown yeah the key difference here being that these icons actually change nature when filled or not, instead of just changing color. I think it makes sense as well.

**Review by daneah — APPROVED** [review]

**Comment by chrisjbrown** [comment]
> @rehanabbasi @chrisjbrown yeah the key difference here being that these icons actually change nature when filled or not, instead of just changing color. I think it makes sense as well.

yeah when i actually looked at the icon didn't seem like any way to get that desired fidelity via the consumer. looks good now

**Pull request merged**
