### PR TITLE
Link: display blue outline on focus

### PR DESCRIPTION
**Pull request by NazimHAli**
**This change:** (check at least one)

- [ ] Adds a new feature
- [x] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
Resolves accessibility/display issue https://github.com/ithaka/pharos/issues/485

Blue outline not rendered in Chrome when focusing on a link with a nested heading.

**How does this change work?**
Sets the `display` value to `inline-block` so that it renders the layout and elements dimensions (margin/padding) are applied properly.

### CODE REVIEW

**Review by chrisjbrown — APPROVED** [review]
nice. works for me 👍

**Review by daneah — COMMENTED** [review]
@NazimHAli can you think of ways that links going from `inline` to `inline-block` could break existing usages?

**Comment by NazimHAli** [comment]
> @NazimHAli can you think of ways that links going from `inline` to `inline-block` could break existing usages?

I was thinking about this and tried to find examples to determine if this was a breaking change. One change that I can think of is with `inline`, the default `width` of the link element is set to `auto`, but with `inline-block`, it will be set to the width of the elements content.

The current `inline`:

Screen Shot 2023-02-02 at 15 24 13

With `inline-block`:

Screen Shot 2023-02-02 at 15 26 14

**Comment by daneah** [comment]
@NazimHAli That's a good one to think about. What I'm interpreting there is that headings that are linked will have their default `block` value forced to `inline-block`, which I don't think is right for headings. Is that accurate?

**Comment by NazimHAli** [comment]
> @NazimHAli That's a good one to think about. What I'm interpreting there is that headings that are linked will have their default `block` value forced to `inline-block`, which I don't think is right for headings. Is that accurate?

It's for the link element, not the header. Another idea is setting it only for links with nested header. It could be the case where the layout isn't rendered instead of all links.

**Comment by daneah** [comment]
@NazimHAli I understand, I was wondering if the heading gets wrapped in the link which affects its display status in turn.

**Comment by NazimHAli** [comment]
@daneah I ran into another oddity, replacing outer style `solid` with `auto` on 243 https://github.com/ithaka/pharos/blob/e50a0f54fe8104b0eae007284767df4d00f46227/packages/pharos/src/utils/scss/_mixins.scss#L241-L246

Renders a different outline, makes me wonder if there's some other styling issue:

pharos jstor org_storybooks_wc_iframe html_id=components-link--visited-link-heading viewMode=story

**Comment by chrisjbrown** [comment]
What was the problem with `inline-block` for the link element? that looks correct for me with `pharos-heading` `div` `span` `just text` slotted in

**Comment by daneah** [comment]
@chrisjbrown a native link around a native heading behaves differently, keeping the full `block` nature of the heading:

Screen Shot 2023-02-03 at 10 42 39

I am not inclined to deviate from this as it will not match people's general expectations.

**Comment by chrisjbrown** [comment]
> @chrisjbrown a native link around a native heading behaves differently, keeping the full `block` nature of the heading:
> I am not inclined to deviate from this as it will not match people's general expectations.

🤔  i see

**Comment by chrisjbrown** [comment]
playing around here.
https://stackblitz.com/edit/pharos-repro-sandbox-4zb9ny?file=src/App.vue

still not sure why pharos doesn't do this in chrome as is 😕

**Comment by NazimHAli** [comment]
@daneah @chrisjbrown any reason we shouldn't set the default `display` for`#link-element` to `block` instead of `inline-block` here?

**Comment by daneah** [comment]
@NazimHAli I think setting links to `display: block` is even more likely to significantly break (almost all?) current usage, as links are typically `display: inline`.

**Comment by NazimHAli** [comment]
> Unless you're saying the host element will still be `display: inline`?

Yes, that's what I mean. Keep `:host` as is, and update `#link-element` to have `display: block`.

**Comment by NazimHAli** [comment]
@daneah setting just the element as a `block` did not work as I'd hoped, it still affects links in general. The only scalable solutions I can think of right now is to create a variant that sets the display for this use case.

**Pull request closed without merging**
