### PR TITLE
Pin Yarn and Node versions, and update relevant quickstart docs

### PR DESCRIPTION
**Pull request by drewgingerich**
**This change:** (check at least one)

- [ ] Adds a new feature
- [ ] Fixes a bug
- [x] Improves maintainability
- [x] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [ ] Test suite(s) passing?
- [ ] Code coverage maximal?
- [ ] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**

This PR tries to remove a few areas of friction I noticed while setting up the project for my first time.

**How does this change work?**

This PR uses Yarn's built-in version management ([docs](https://yarnpkg.com/cli/set/version)) to pin the Yarn version to Yarn Classic. This means developers using Yarn Berry won't need to do any configuration: Yarn will automatically run using the pinned Yarn version. The pinned Yarn version is actually committed for maximum reproducibility.

This PR commits the `.tool-versions` file generated by `asdf` ([docs](https://asdf-vm.com/manage/configuration.html)). This means the correct Node.js version will be automatically selected by `asdf` users if already installed, and easily installed using just `asdf install` if not. `asdf` does not work with the current `.nvmrc` file: even though `asdf` can be configured to read it ([docs](https://asdf-vm.com/manage/configuration.html#legacy-version-file)), `asdf` expects a fully-qualified semver version while the `.nvmrc` only lists the major version.

This PR updates the quickstart documentation to include information about using `asdf`, a bit more context around using Yarn, and removes the suggestion to install `Typescript` globally because `Typescript` is already listed as a development dependency in all packages.

### CODE REVIEW

**Review by chrisjbrown — APPROVED** [review]

**Comment by drewgingerich** [comment]
Is this PR ready to merge, or does it need another reviewer to remove the `status/code review` label? Based on the contribution docs it seems ready to go. @jialin-he Any chance you have a moment to look over the changes?

**Comment by drewgingerich** [comment]
@dane @chrisjbrown 
> Is this PR ready to merge, or does it need another reviewer to remove the `status/code review` label? Based on the contribution docs it seems ready to go. @jialin-he Any chance you have a moment to look over the changes?

**Comment by chrisjbrown** [comment]
> @dane @chrisjbrown
> 
> > Is this PR ready to merge, or does it need another reviewer to remove the `status/code review` label? Based on the contribution docs it seems ready to go. @jialin-he Any chance you have a moment to look over the changes?

is good to go for me

**Comment by dane** [comment]
I trust you all. Merge away 👍

**Comment by daneah** [comment]
Ha! Thanks for your grace other @dane 😅

**Pull request merged**
